import {MigrationInterface, QueryRunner} from "typeorm";

export class initialSchema1621935406620 implements MigrationInterface {
    name = 'initialSchema1621935406620'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `order` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `cartId` int UNSIGNED NOT NULL, `userId` int UNSIGNED NOT NULL, `paymentType` enum ('cod', 'paytm', 'card') NOT NULL DEFAULT 'cod', `paymentStatus` enum ('cod', 'paytm', 'card') NOT NULL DEFAULT 'cod', `transactionId` varchar(20) NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, UNIQUE INDEX `REL_fe3963d525b2ee03ba471953a7` (`cartId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `cart` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `userId` int UNSIGNED NOT NULL, `status` enum ('active', 'inactive') NOT NULL DEFAULT 'active', `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `inventory` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `costPrice` decimal(10,2) UNSIGNED NOT NULL, `retailPrice` decimal(10,2) UNSIGNED NOT NULL, `initialStock` int UNSIGNED NOT NULL, `itemsLeft` int UNSIGNED NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `public_asset` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `fileName` varchar(70) NOT NULL, `fileType` enum ('image', 'video', 'pdf') NOT NULL DEFAULT 'image', `uri` varchar(120) NOT NULL, `attributes` text NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `product_asset` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(80) NOT NULL, `description` varchar(200) NOT NULL, `productId` int UNSIGNED NOT NULL, `assetId` int UNSIGNED NOT NULL, `isDefault` tinyint NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, UNIQUE INDEX `REL_5888ac17b317b93378494a1062` (`assetId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `review` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(50) NOT NULL, `description` varchar(500) NOT NULL, `rating` tinyint UNSIGNED NOT NULL, `productClassId` int UNSIGNED NOT NULL, `status` enum ('active', 'inactive') NOT NULL DEFAULT 'active', `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `category` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(80) NOT NULL, `description` varchar(150) NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `sub_category` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `categoryId` int UNSIGNED NOT NULL, `name` varchar(80) NOT NULL, `description` varchar(150) NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `product_class` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(30) NOT NULL, `description` varchar(500) NOT NULL, `brandName` varchar(30) NOT NULL, `rating` tinyint UNSIGNED NOT NULL, `subCategoryId` int UNSIGNED NOT NULL, `status` enum ('active', 'inactive') NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `product` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(30) NOT NULL, `description` varchar(500) NOT NULL, `color` varchar(10) NOT NULL, `size` varchar(10) NOT NULL, `otherAttributes` text NOT NULL, `status` enum ('active', 'inactive') NOT NULL DEFAULT 'active', `productClassId` int UNSIGNED NOT NULL, `inventoryId` int UNSIGNED NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, UNIQUE INDEX `REL_0d5b00db0b857ac0d8c4dd7243` (`inventoryId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `favorite` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `userId` int UNSIGNED NOT NULL, `productId` int UNSIGNED NOT NULL, `status` enum ('active', 'inactive') NOT NULL DEFAULT 'active', `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `app_role` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `roleName` enum ('admin', 'customer') NOT NULL DEFAULT 'customer', `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `app_user` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `email` varchar(60) NOT NULL, `password` varchar(20) NOT NULL, `roleId` int UNSIGNED NOT NULL, `accountVerified` tinyint NOT NULL DEFAULT 0, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `discount` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(20) NOT NULL, `coupon` varchar(10) NOT NULL, `description` varchar(150) NOT NULL, `status` enum ('active', 'inactive') NOT NULL DEFAULT 'active', `discountRate` decimal(5,2) UNSIGNED NOT NULL, `minimumOrderValue` decimal(10,2) UNSIGNED NOT NULL, `minimumOrderQuantity` int UNSIGNED NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `cart_item` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `cartId` int UNSIGNED NOT NULL, `productId` int UNSIGNED NOT NULL, `discountId` int UNSIGNED NOT NULL, `status` enum ('active', 'inactive') NOT NULL DEFAULT 'active', `sellingPrice` decimal(10,2) UNSIGNED NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `state` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(30) NOT NULL, `abbreveation` varchar(5) NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `city` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(30) NOT NULL, `stateId` int UNSIGNED NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `event_promo` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(45) NOT NULL, `description` varchar(200) NOT NULL, `status` enum ('active', 'inactive') NOT NULL DEFAULT 'active', `eventType` enum ('exclusive', 'hot-deal') NOT NULL DEFAULT 'exclusive', `carouselImageId` int UNSIGNED NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, UNIQUE INDEX `REL_f53030e08ef005eff656cdf6e7` (`carouselImageId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `event_collection` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `eventPromoId` int UNSIGNED NOT NULL, `status` enum ('active', 'inactive') NOT NULL DEFAULT 'active', `productId` int UNSIGNED NOT NULL, `discountId` int UNSIGNED NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, UNIQUE INDEX `REL_eb8a7a72f145237169cff1341f` (`eventPromoId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_profile` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `userId` int UNSIGNED NOT NULL, `firstName` varchar(255) NOT NULL, `middleName` varchar(255) NOT NULL, `lastName` varchar(255) NOT NULL, `gender` enum ('male', 'female') NOT NULL DEFAULT 'male', `dateOfBirth` date NOT NULL, `address` varchar(400) NOT NULL, `mobile` varchar(15) NOT NULL, `profileImageId` int UNSIGNED NOT NULL, `cityId` int UNSIGNED NOT NULL, `createdById` int UNSIGNED NULL, `updatedById` int UNSIGNED NULL, `loggerCreatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `loggerUpdatedon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `loggerCreatedbyid` int UNSIGNED NULL, `loggerUpdatedbyid` int UNSIGNED NULL, UNIQUE INDEX `REL_51cb79b5555effaf7d69ba1cff` (`userId`), UNIQUE INDEX `REL_9a0a35198c95ecf4ef632aef51` (`profileImageId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `order` ADD CONSTRAINT `FK_fe3963d525b2ee03ba471953a7c` FOREIGN KEY (`cartId`) REFERENCES `cart`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `order` ADD CONSTRAINT `FK_de6fa8b07fd7e0a8bf9edb5eb38` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `order` ADD CONSTRAINT `FK_8289699b21674ff4897a9406af0` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cart` ADD CONSTRAINT `FK_756f53ab9466eb52a52619ee019` FOREIGN KEY (`userId`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cart` ADD CONSTRAINT `FK_eaca17862ea338f633669c95211` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cart` ADD CONSTRAINT `FK_476b318963147ddc70f5f973ea1` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `inventory` ADD CONSTRAINT `FK_a35b2af7fa30e71e4229e3d4e22` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `inventory` ADD CONSTRAINT `FK_2a708a50461d83a849cc3a1a950` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `public_asset` ADD CONSTRAINT `FK_d2cb10d9d8003686d7238a7fe09` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `public_asset` ADD CONSTRAINT `FK_2dde6993ee2702e2b2c1ef4a54f` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product_asset` ADD CONSTRAINT `FK_0d1294f5c22a56da7845ebab72c` FOREIGN KEY (`productId`) REFERENCES `product`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product_asset` ADD CONSTRAINT `FK_5888ac17b317b93378494a10620` FOREIGN KEY (`assetId`) REFERENCES `public_asset`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product_asset` ADD CONSTRAINT `FK_d208fdcf2bcbbac00e05c63d63e` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product_asset` ADD CONSTRAINT `FK_0390949a05bc9edf46ec0d28298` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `review` ADD CONSTRAINT `FK_0835d8e0e7e3e7a30fbea072909` FOREIGN KEY (`productClassId`) REFERENCES `product_class`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `review` ADD CONSTRAINT `FK_7f1febb5465b721169034ec247f` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `review` ADD CONSTRAINT `FK_b2b3ce1c2427b249ba402057ae5` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `category` ADD CONSTRAINT `FK_50c69cdc9b3e7494784a2fa2db4` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `category` ADD CONSTRAINT `FK_a5d7b5b0fc1f7358541b14b242d` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `sub_category` ADD CONSTRAINT `FK_51b8c0b349725210c4bd8b9b7a7` FOREIGN KEY (`categoryId`) REFERENCES `category`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `sub_category` ADD CONSTRAINT `FK_0adcf300b01b952ae7d6957c33c` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `sub_category` ADD CONSTRAINT `FK_e7a68417dfe2e759494a2bafab6` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product_class` ADD CONSTRAINT `FK_72d75d16227e0f6a9514743c764` FOREIGN KEY (`subCategoryId`) REFERENCES `sub_category`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product_class` ADD CONSTRAINT `FK_d85fc6b081563a75198e12fb1fd` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product_class` ADD CONSTRAINT `FK_aeda705c538ed69211849796572` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product` ADD CONSTRAINT `FK_67ad2dcc7fd5b5fe769690104cd` FOREIGN KEY (`productClassId`) REFERENCES `product_class`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product` ADD CONSTRAINT `FK_0d5b00db0b857ac0d8c4dd72437` FOREIGN KEY (`inventoryId`) REFERENCES `inventory`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product` ADD CONSTRAINT `FK_806302f2d4da2a0c27eedbf34fe` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `product` ADD CONSTRAINT `FK_9c29670ff9dd3fd43cf20733c19` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `favorite` ADD CONSTRAINT `FK_83b775fdebbe24c29b2b5831f2d` FOREIGN KEY (`userId`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `favorite` ADD CONSTRAINT `FK_b8e337759b77baa0a4055d1894e` FOREIGN KEY (`productId`) REFERENCES `product`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `favorite` ADD CONSTRAINT `FK_7c0b853c9ed3d098933ab4892f1` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `favorite` ADD CONSTRAINT `FK_5c5b726a4d57f80e9e36e9103c7` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `app_role` ADD CONSTRAINT `FK_79a579c65d8a48ec23d4d0bbc1f` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `app_role` ADD CONSTRAINT `FK_97ea6775f31766da5d44270435e` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `app_user` ADD CONSTRAINT `FK_3668eab64dbf196a630661f1f21` FOREIGN KEY (`roleId`) REFERENCES `app_role`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `app_user` ADD CONSTRAINT `FK_97bd7a216aa20e2e1189710a3fa` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `app_user` ADD CONSTRAINT `FK_1236799701164b3ef3c2d427c50` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `discount` ADD CONSTRAINT `FK_5b3957849aad68f2e1ba4bb5630` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `discount` ADD CONSTRAINT `FK_6ca78d7d85aa0dfe1e9b125df9f` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cart_item` ADD CONSTRAINT `FK_29e590514f9941296f3a2440d39` FOREIGN KEY (`cartId`) REFERENCES `cart`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cart_item` ADD CONSTRAINT `FK_75db0de134fe0f9fe9e4591b7bf` FOREIGN KEY (`productId`) REFERENCES `product`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cart_item` ADD CONSTRAINT `FK_c2c33f92cbe3bf13b728bd76cdf` FOREIGN KEY (`discountId`) REFERENCES `discount`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cart_item` ADD CONSTRAINT `FK_6b4a75b8c2f216532626770c5d7` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cart_item` ADD CONSTRAINT `FK_82bcd725a1c1069d32527827b2f` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `state` ADD CONSTRAINT `FK_2a78c0831744c8ad063fbd65c4e` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `state` ADD CONSTRAINT `FK_1c5a1a7d9dcdcd9944a6db9be76` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `city` ADD CONSTRAINT `FK_e99de556ee56afe72154f3ed04a` FOREIGN KEY (`stateId`) REFERENCES `state`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `city` ADD CONSTRAINT `FK_0e5b4733e944fc94c53596eaf95` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `city` ADD CONSTRAINT `FK_c763694681c8b6033ab3fef5f9f` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `event_promo` ADD CONSTRAINT `FK_f53030e08ef005eff656cdf6e78` FOREIGN KEY (`carouselImageId`) REFERENCES `public_asset`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `event_promo` ADD CONSTRAINT `FK_09058367c6760747ed382e6dc5a` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `event_promo` ADD CONSTRAINT `FK_2e0170c2823cb1fe9a3f899ec8f` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `event_collection` ADD CONSTRAINT `FK_eb8a7a72f145237169cff1341f6` FOREIGN KEY (`eventPromoId`) REFERENCES `event_promo`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `event_collection` ADD CONSTRAINT `FK_55242f0d1c99bd53b6f9572e96d` FOREIGN KEY (`productId`) REFERENCES `product`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `event_collection` ADD CONSTRAINT `FK_ab3f3a2f1340ae06a28024063eb` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `event_collection` ADD CONSTRAINT `FK_3231724a46b06efcdfca4e4a670` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_profile` ADD CONSTRAINT `FK_51cb79b5555effaf7d69ba1cff9` FOREIGN KEY (`userId`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_profile` ADD CONSTRAINT `FK_9a0a35198c95ecf4ef632aef517` FOREIGN KEY (`profileImageId`) REFERENCES `public_asset`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_profile` ADD CONSTRAINT `FK_129f135f39cf34b3b2d012ddacf` FOREIGN KEY (`cityId`) REFERENCES `city`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_profile` ADD CONSTRAINT `FK_837a9d606a5ad10d7a39a3bb0df` FOREIGN KEY (`createdById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_profile` ADD CONSTRAINT `FK_0d39fc868f860ee6bc8847d0c17` FOREIGN KEY (`updatedById`) REFERENCES `app_user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `user_profile` DROP FOREIGN KEY `FK_0d39fc868f860ee6bc8847d0c17`");
        await queryRunner.query("ALTER TABLE `user_profile` DROP FOREIGN KEY `FK_837a9d606a5ad10d7a39a3bb0df`");
        await queryRunner.query("ALTER TABLE `user_profile` DROP FOREIGN KEY `FK_129f135f39cf34b3b2d012ddacf`");
        await queryRunner.query("ALTER TABLE `user_profile` DROP FOREIGN KEY `FK_9a0a35198c95ecf4ef632aef517`");
        await queryRunner.query("ALTER TABLE `user_profile` DROP FOREIGN KEY `FK_51cb79b5555effaf7d69ba1cff9`");
        await queryRunner.query("ALTER TABLE `event_collection` DROP FOREIGN KEY `FK_3231724a46b06efcdfca4e4a670`");
        await queryRunner.query("ALTER TABLE `event_collection` DROP FOREIGN KEY `FK_ab3f3a2f1340ae06a28024063eb`");
        await queryRunner.query("ALTER TABLE `event_collection` DROP FOREIGN KEY `FK_55242f0d1c99bd53b6f9572e96d`");
        await queryRunner.query("ALTER TABLE `event_collection` DROP FOREIGN KEY `FK_eb8a7a72f145237169cff1341f6`");
        await queryRunner.query("ALTER TABLE `event_promo` DROP FOREIGN KEY `FK_2e0170c2823cb1fe9a3f899ec8f`");
        await queryRunner.query("ALTER TABLE `event_promo` DROP FOREIGN KEY `FK_09058367c6760747ed382e6dc5a`");
        await queryRunner.query("ALTER TABLE `event_promo` DROP FOREIGN KEY `FK_f53030e08ef005eff656cdf6e78`");
        await queryRunner.query("ALTER TABLE `city` DROP FOREIGN KEY `FK_c763694681c8b6033ab3fef5f9f`");
        await queryRunner.query("ALTER TABLE `city` DROP FOREIGN KEY `FK_0e5b4733e944fc94c53596eaf95`");
        await queryRunner.query("ALTER TABLE `city` DROP FOREIGN KEY `FK_e99de556ee56afe72154f3ed04a`");
        await queryRunner.query("ALTER TABLE `state` DROP FOREIGN KEY `FK_1c5a1a7d9dcdcd9944a6db9be76`");
        await queryRunner.query("ALTER TABLE `state` DROP FOREIGN KEY `FK_2a78c0831744c8ad063fbd65c4e`");
        await queryRunner.query("ALTER TABLE `cart_item` DROP FOREIGN KEY `FK_82bcd725a1c1069d32527827b2f`");
        await queryRunner.query("ALTER TABLE `cart_item` DROP FOREIGN KEY `FK_6b4a75b8c2f216532626770c5d7`");
        await queryRunner.query("ALTER TABLE `cart_item` DROP FOREIGN KEY `FK_c2c33f92cbe3bf13b728bd76cdf`");
        await queryRunner.query("ALTER TABLE `cart_item` DROP FOREIGN KEY `FK_75db0de134fe0f9fe9e4591b7bf`");
        await queryRunner.query("ALTER TABLE `cart_item` DROP FOREIGN KEY `FK_29e590514f9941296f3a2440d39`");
        await queryRunner.query("ALTER TABLE `discount` DROP FOREIGN KEY `FK_6ca78d7d85aa0dfe1e9b125df9f`");
        await queryRunner.query("ALTER TABLE `discount` DROP FOREIGN KEY `FK_5b3957849aad68f2e1ba4bb5630`");
        await queryRunner.query("ALTER TABLE `app_user` DROP FOREIGN KEY `FK_1236799701164b3ef3c2d427c50`");
        await queryRunner.query("ALTER TABLE `app_user` DROP FOREIGN KEY `FK_97bd7a216aa20e2e1189710a3fa`");
        await queryRunner.query("ALTER TABLE `app_user` DROP FOREIGN KEY `FK_3668eab64dbf196a630661f1f21`");
        await queryRunner.query("ALTER TABLE `app_role` DROP FOREIGN KEY `FK_97ea6775f31766da5d44270435e`");
        await queryRunner.query("ALTER TABLE `app_role` DROP FOREIGN KEY `FK_79a579c65d8a48ec23d4d0bbc1f`");
        await queryRunner.query("ALTER TABLE `favorite` DROP FOREIGN KEY `FK_5c5b726a4d57f80e9e36e9103c7`");
        await queryRunner.query("ALTER TABLE `favorite` DROP FOREIGN KEY `FK_7c0b853c9ed3d098933ab4892f1`");
        await queryRunner.query("ALTER TABLE `favorite` DROP FOREIGN KEY `FK_b8e337759b77baa0a4055d1894e`");
        await queryRunner.query("ALTER TABLE `favorite` DROP FOREIGN KEY `FK_83b775fdebbe24c29b2b5831f2d`");
        await queryRunner.query("ALTER TABLE `product` DROP FOREIGN KEY `FK_9c29670ff9dd3fd43cf20733c19`");
        await queryRunner.query("ALTER TABLE `product` DROP FOREIGN KEY `FK_806302f2d4da2a0c27eedbf34fe`");
        await queryRunner.query("ALTER TABLE `product` DROP FOREIGN KEY `FK_0d5b00db0b857ac0d8c4dd72437`");
        await queryRunner.query("ALTER TABLE `product` DROP FOREIGN KEY `FK_67ad2dcc7fd5b5fe769690104cd`");
        await queryRunner.query("ALTER TABLE `product_class` DROP FOREIGN KEY `FK_aeda705c538ed69211849796572`");
        await queryRunner.query("ALTER TABLE `product_class` DROP FOREIGN KEY `FK_d85fc6b081563a75198e12fb1fd`");
        await queryRunner.query("ALTER TABLE `product_class` DROP FOREIGN KEY `FK_72d75d16227e0f6a9514743c764`");
        await queryRunner.query("ALTER TABLE `sub_category` DROP FOREIGN KEY `FK_e7a68417dfe2e759494a2bafab6`");
        await queryRunner.query("ALTER TABLE `sub_category` DROP FOREIGN KEY `FK_0adcf300b01b952ae7d6957c33c`");
        await queryRunner.query("ALTER TABLE `sub_category` DROP FOREIGN KEY `FK_51b8c0b349725210c4bd8b9b7a7`");
        await queryRunner.query("ALTER TABLE `category` DROP FOREIGN KEY `FK_a5d7b5b0fc1f7358541b14b242d`");
        await queryRunner.query("ALTER TABLE `category` DROP FOREIGN KEY `FK_50c69cdc9b3e7494784a2fa2db4`");
        await queryRunner.query("ALTER TABLE `review` DROP FOREIGN KEY `FK_b2b3ce1c2427b249ba402057ae5`");
        await queryRunner.query("ALTER TABLE `review` DROP FOREIGN KEY `FK_7f1febb5465b721169034ec247f`");
        await queryRunner.query("ALTER TABLE `review` DROP FOREIGN KEY `FK_0835d8e0e7e3e7a30fbea072909`");
        await queryRunner.query("ALTER TABLE `product_asset` DROP FOREIGN KEY `FK_0390949a05bc9edf46ec0d28298`");
        await queryRunner.query("ALTER TABLE `product_asset` DROP FOREIGN KEY `FK_d208fdcf2bcbbac00e05c63d63e`");
        await queryRunner.query("ALTER TABLE `product_asset` DROP FOREIGN KEY `FK_5888ac17b317b93378494a10620`");
        await queryRunner.query("ALTER TABLE `product_asset` DROP FOREIGN KEY `FK_0d1294f5c22a56da7845ebab72c`");
        await queryRunner.query("ALTER TABLE `public_asset` DROP FOREIGN KEY `FK_2dde6993ee2702e2b2c1ef4a54f`");
        await queryRunner.query("ALTER TABLE `public_asset` DROP FOREIGN KEY `FK_d2cb10d9d8003686d7238a7fe09`");
        await queryRunner.query("ALTER TABLE `inventory` DROP FOREIGN KEY `FK_2a708a50461d83a849cc3a1a950`");
        await queryRunner.query("ALTER TABLE `inventory` DROP FOREIGN KEY `FK_a35b2af7fa30e71e4229e3d4e22`");
        await queryRunner.query("ALTER TABLE `cart` DROP FOREIGN KEY `FK_476b318963147ddc70f5f973ea1`");
        await queryRunner.query("ALTER TABLE `cart` DROP FOREIGN KEY `FK_eaca17862ea338f633669c95211`");
        await queryRunner.query("ALTER TABLE `cart` DROP FOREIGN KEY `FK_756f53ab9466eb52a52619ee019`");
        await queryRunner.query("ALTER TABLE `order` DROP FOREIGN KEY `FK_8289699b21674ff4897a9406af0`");
        await queryRunner.query("ALTER TABLE `order` DROP FOREIGN KEY `FK_de6fa8b07fd7e0a8bf9edb5eb38`");
        await queryRunner.query("ALTER TABLE `order` DROP FOREIGN KEY `FK_fe3963d525b2ee03ba471953a7c`");
        await queryRunner.query("DROP INDEX `REL_9a0a35198c95ecf4ef632aef51` ON `user_profile`");
        await queryRunner.query("DROP INDEX `REL_51cb79b5555effaf7d69ba1cff` ON `user_profile`");
        await queryRunner.query("DROP TABLE `user_profile`");
        await queryRunner.query("DROP INDEX `REL_eb8a7a72f145237169cff1341f` ON `event_collection`");
        await queryRunner.query("DROP TABLE `event_collection`");
        await queryRunner.query("DROP INDEX `REL_f53030e08ef005eff656cdf6e7` ON `event_promo`");
        await queryRunner.query("DROP TABLE `event_promo`");
        await queryRunner.query("DROP TABLE `city`");
        await queryRunner.query("DROP TABLE `state`");
        await queryRunner.query("DROP TABLE `cart_item`");
        await queryRunner.query("DROP TABLE `discount`");
        await queryRunner.query("DROP TABLE `app_user`");
        await queryRunner.query("DROP TABLE `app_role`");
        await queryRunner.query("DROP TABLE `favorite`");
        await queryRunner.query("DROP INDEX `REL_0d5b00db0b857ac0d8c4dd7243` ON `product`");
        await queryRunner.query("DROP TABLE `product`");
        await queryRunner.query("DROP TABLE `product_class`");
        await queryRunner.query("DROP TABLE `sub_category`");
        await queryRunner.query("DROP TABLE `category`");
        await queryRunner.query("DROP TABLE `review`");
        await queryRunner.query("DROP INDEX `REL_5888ac17b317b93378494a1062` ON `product_asset`");
        await queryRunner.query("DROP TABLE `product_asset`");
        await queryRunner.query("DROP TABLE `public_asset`");
        await queryRunner.query("DROP TABLE `inventory`");
        await queryRunner.query("DROP TABLE `cart`");
        await queryRunner.query("DROP INDEX `REL_fe3963d525b2ee03ba471953a7` ON `order`");
        await queryRunner.query("DROP TABLE `order`");
    }

}
